### ISSUE TITLE
OBShapedButton太多内存暴涨

### ISSUE THREAD

**Issue by sesameImmortals** [yfGit/IrregularShapeClick#1]
我看你的这个demo,运气起来内存直接飙到390.为何? OBShapedButton的问题??

**Comment by yfGit** [comment]
不好意思, 看见的晚了.
谢谢你的提醒, 之前只关注效果了.
找到的问题是我的图片本来像素太高了. 33张 * 1644 × 1541 pixels的图片.一开始找的整图素材的问题. 哪怕换成系统的UIImageView也一样. 你可以换下像素低的再控制下数量就OK了
